version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:15.11.5-ce.0'
    container_name: gitlab
    restart: always
    hostname: '192.168.254.131'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.254.131'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

  nexus:
    image: 'sonatype/nexus'
    container_name: nexus
    ports:
      - '8081:8081'
    volumes:
      - '$NEXUS_DATA/nexus-data:/nexus-data'

  postgres:
    image: 'postgres:9.3'
    container_name: postgres
    environment:
      POSTGRES_DB: 'jiradb'
      POSTGRES_USER: 'jira'
      POSTGRES_PASSWORD: 'jira'
    ports:
      - '5432:5432'
    volumes:
      - '$POSTGRES_DATA/:/var/lib/postgres/data'
